server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driverClassName: com.mysql.jdbc.Driver
#      url: jdbc:mysql://rm-bp1053g87747113wxo.mysql.rds.aliyuncs.com:3306/mt_test_trade?characterEncoding=utf8
#      username: test_web
#      password: test@mt123
      url: jdbc:mysql://localhost:3306/bjyc?characterEncoding=utf8
      username: root
      password: admin
      initialSize: 5
      minIdle: 5
      maxActive: 5
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true

logging:
  level:
    com.bjyc.inter: debug